### ISSUE TITLE
Improve description link for GDP total PPP2011

### ISSUE THREAD

**Issue by olarosling** [open-numbers/ddf--gapminder--systema_globalis#1]
http://data.worldbank.org/indicator/NY.GDP.PCAP.KD

The world bank link used, is pointing to a GDOP definition exressed in PPP 2005, which is confusing as our default uses PPP2011 
WB hasn't updated there total GDP series online, it seams like,
so we should either check if they have done so,
or find a nother age explaining,
or set up one our self.

**Comment by jheeffer** [comment]
long long ago, probably irrelevant
