### ISSUE TITLE
Missing drillup and down columns in lists

### ISSUE THREAD

**Issue by jheeffer** [open-numbers/ddf--gapminder--systema_globalis#12]
Missing:

column `global` in *ddf--list--geo--country.csv*.

if https://github.com/open-numbers/ddf--gapminder--systema_globalis/issues/11 is an actual valid issue, then we're also missing 

column `global` in *ddf--list--geo--world_4region.csv*.

**Comment by olarosling** [comment]
I removed dril ups as they should be derived from drilldowns
