### ISSUE TITLE
un_state is missing in index

### ISSUE THREAD

**Issue by jheeffer** [open-numbers/ddf--gapminder--systema_globalis#13]
If I want to find population of geo's with subdimension un_state, I cannot find them through the index. I might be able to find which geo's are un_states by looking at is.un_state value_concept, but where do I find population data for these? I know it's in `ddf--data_for--population--by--country--year.csv` of course but I mean, through the logic of the index, how would a computer find where the data is?

So, I guess un_state should have occurences in the geo-column, pointing to the list--countries.csv file for property-definitins and the relevant data-files for measures.

**Comment by olarosling** [comment]
How do you mean? un_state is missing where? 
row 23
is.un_state	country
https://github.com/open-numbers/ddf--gapminder--systema_globalis/blob/master/ddf--index.csv

**Comment by olarosling** [comment]
Added rows https://github.com/open-numbers/ddf--gapminder--systema_globalis/blob/master/ddf--index.csv
