### ISSUE TITLE
ddf--index.csv should enumerate all properties of list files

### ISSUE THREAD

**Issue by olarosling** [open-numbers/ddf--gapminder--systema_globalis#4]
https://github.com/open-numbers/ddf--gapminder--systema_globalis/blob/master/ddf--index.csv

needs rows derived from the properties of the list files
so the index file is a complete enumeraiotn of all values possible to pull from this dataset, and in which file to pull them with what key.

**Comment by olarosling** [comment]
@valorkin I will fix the index file as you requested, and FYI I will also include this change.

**Comment by valorkin** [comment]
awesome, thanks!

**Comment by olarosling** [comment]
Done. I believe...
