### ISSUE TITLE
Working hours per week Rwanda 2017

### ISSUE THREAD

**Issue by jheeffer** [open-numbers/ddf--gapminder--systema_globalis#66]
ILO source DDFcsv has correct data (32.7067): https://github.com/open-numbers/ddf--ilo--ilostat/blob/autogenerated/ddf--datapoints--how_temp_noc_nb--by--ref_area--classif1--time.csv#L1405

SG DDFcsv has incorrect data (172.xxx): https://github.com/open-numbers/ddf--gapminder--systema_globalis/blob/master/ddf--datapoints--working_hours_per_week--by--geo--time.csv#L1389

This wrong data was in a previous version of ILO: https://github.com/open-numbers/ddf--ilo--ilostat/blame/a4897d8b11ab5812bf524e92d54119fa4c41c906/ddf--datapoints--how_temp_noc_nb--by--ref_area--classif1--time.csv#L1389

Why did the new ILO version not propagate to SG?

**Comment by jheeffer** [comment]
SG recipe is turned off for quite some time since manual work is done on GBD indicators.

**Comment by semio** [comment]
The recipe was enabled and now data are same in ILO source and SG autogen.
